Refactoring

diff --git a/src/usr/bin/tmpfize b/src/usr/bin/tmpfize
--- a/src/usr/bin/tmpfize
+++ b/src/usr/bin/tmpfize
@@ -10,21 +10,21 @@ function get_name {
 }
 
 # Logging
-function out {
-	[ $1 -le $verbosity ] && echo "$2"
+function log {
+	[ $1 -le $pref_log_level ] && echo "$2"
 }
 
 # Print help page
 function show_help {
 echo "
-Usage: $0 [-hrvpu] [-t interval] TARGET_DIR[.tar.gz] -- [COMMAND]
+Usage: $0 [-hrvpu] [-t interval] SOURCE_DIR[.tar.gz] -- [COMMAND]
 
 Technical:
  -h		- Show this page.
  -v		- Show info messages.
 
 Mount Settings:
- TARGET_DIR	- Path or name of directory that will be moved to tmpfs.
+ SOURCE_DIR	- Path or name of directory that will be moved to tmpfs.
 
  -t interval	- Synchronize interval in seconds (default: 30, 0 to disable).
 		  
@@ -44,42 +44,36 @@ Mount control:
 }
 
 # Check parameters
-if [ $# -eq 0 ]; then
-	show_help
-	exit 1
-fi
+[ $# -eq 0 ] && show_help && exit 1
 
 # Defaults
-verbosity=0
-sync_interval=30
+pref_log_level=0
+pref_sync_delay=30
 
 # Parsing arguments
 while getopts ":t:rhvpu" opt; do
 	case $opt in
-		t) sync_interval="$OPTARG";;
-		r) read_only="true" ;;
-		v) verbosity=$((verbosity+1)) ;;
-		p) if [ "$save_ram_copy" ]; then
-			save_disk_copy="true"
-		   else
-			save_ram_copy="true"
-		   fi
-		   ;;
-		u) unmount="true" ;;
-			
+		t) pref_sync_delay="$OPTARG";;
+		r) pref_read_only="true" ;;
+		v) pref_log_level=$((pref_log_level+1)) ;;
+		p) [ "$pref_save_in_ram" ] \
+			&& pref_save_on_disk="true" \
+			|| pref_save_in_ram="true" ;;
+		u) mode_unmount="true" ;;
 		*) show_help; exit ;;
 	esac
 done
 shift $((OPTIND-1))
 
+# Iterate through all arguments until "--"
 while [ "$1" ]; do
 	if [ "$1" == "--" ]; then
 		shift
-		execute="$@"
+		pref_execute="$@"
 		break
 	fi
 
-	target_dir_list=(${target_dir_list[@]} $1)
+	source_list=(${source_list[@]} $1)
 	shift
 done
 
@@ -90,54 +84,53 @@ done
 # Find path to the biggest mounted tmpfs
 tmpfs_mounts=$(mount | grep tmpfs | awk '{print $3}')
 tmpfs_max_size=0
-for tmpfs in $tmpfs_mounts; do
-	size=$(df --output=avail "$tmpfs" | grep -Eo "[0-9]*")
+for tmpfs_mount in $tmpfs_mounts; do
+	size=$(df --output=avail "$tmpfs_mount" | grep -Eo "[0-9]*")
 	if [ $size -gt $tmpfs_max_size ] && \
-	   touch "$tmpfs/tmpfize-test" > /dev/null 2>&1 && \
-	   rm "$tmpfs/tmpfize-test" > /dev/null 2>&1
+	   touch "$tmpfs_mount/tmpfize-test" > /dev/null 2>&1 && \
+	   rm "$tmpfs_mount/tmpfize-test" > /dev/null 2>&1
 	then
 		tmpfs_max_size=$size
-		tmpfize=$tmpfs
+		tmpfs=$tmpfs_mount
 	fi
 done
 
 # Check for successfully found path to tmpfs
-[ ! "$tmpfize" ] && out 0 "[Error] Tmpfs not found..." && exit 1
-out 1 "[Info] Using tmpfs mounted in $tmpfize (size: $tmpfs_max_size KB)"
+[ ! "$tmpfs" ] && log 0 "[Error] Tmpfs not found..." && exit 1
+log 1 "[Info] Using tmpfs mounted in $tmpfs (size: $tmpfs_max_size KB)"
 
 # Target directory
-target_dir=$(realpath -s "$target_dir_list") # /path/to/dir
+source=$(realpath -s "$source_list") # /path/to/dir
 
 # Check for archive extension
-if echo "$target_dir" | grep -qE ".tar.gz$"; then
-	archive="true"
-	target_dir=$(echo "$target_dir" | sed 's/.tar.gz$//g')
+if echo "$source" | grep -qE ".tar.gz$"; then
+	pref_archive="true"
+	source=$(echo "$source" | sed 's/.tar.gz$//g')
 fi
 
-target_dir_path=$(echo "$target_dir" | grep -Eo '^.*\/') # /path/to/
-target_dir_name=$(get_name "$target_dir") # dir
-target_dir_id=$(echo "$target_dir" | md5sum | grep -Eo "^[a-z0-9]+")
+source_path=$(echo "$source" | grep -Eo '^.*\/') # /path/to/
+source_name=$(get_name "$source") # dir
+source_id=$(echo "$source" | md5sum | grep -Eo "^[a-z0-9]+")
 
 # Generating paths
-target_tmpfs="$tmpfize/tmpfize.$target_dir_id"
-backup_dir="$target_dir_path/.tmpfize.$target_dir_id.$target_dir_name"
-target_marker="$target_dir/.tmpfize"
+target="$tmpfs/tmpfize.$source_id"
+backup="$source_path/.tmpfize.$source_id.$source_name"
+marker="$source/.tmpfize"
 
 #############
 # Functions #
 #############
 
 # Unmount previously mounted directory
-if [ "$unmount" ]; then
-	if [ -e "$target_marker" ]; then
-		rm "$target_marker"
-
-		out 1 "Waiting until directory is unmouted..."
-		while [ -e "$backup_dir" ] || [ -e "$target_marker.packing" ]; do
+if [ "$mode_unmount" ]; then
+	if [ -e "$marker" ]; then
+		rm "$marker"
+		log 1 "Waiting until directory is unmouted..."
+		while [ -e "$backup" ] || [ -e "$marker.packing" ]; do
 			sleep 1;
 		done
 	else
-		out 0 "[Error] Directory $target_dir_name is not mounted!"
+		log 0 "[Error] Directory $source_name is not mounted!"
 	fi
 	
 	exit 0
@@ -146,52 +139,50 @@ fi
 # Back sequence
 function back_sequence {
 	if [ "$1" -ge 5 ]; then
-		[ ! "$read_only" ] \
-			&& rsync -ax --delete "$target_tmpfs/" "$backup_dir"
+		[ ! "$pref_read_only" ] \
+			&& rsync -ax --delete "$target/" "$backup"
 	fi
 
 	if [ "$1" -ge 4 ]; then
-		rm "$target_dir"
-		mv "$backup_dir" "$target_dir"
+		rm "$source"
+		mv "$backup" "$source"
 	fi
 	
 	if [ "$1" -eq 3 ]; then
-		rsync -ax "$backup_dir/" "$target_dir"
-		rm -r "$backup_dir"
+		rsync -ax "$backup/" "$source"
+		rm -r "$backup"
 	fi
 
 	if [ "$1" -ge 2 ]; then
-		[ ! "$save_ram_copy" ] && rm -r "$target_tmpfs"
+		[ ! "$pref_save_in_ram" ] && rm -r "$target"
 		
-		if [ "$archive" == "true" ] && [ "$read_only" != "true" ]; then
-			touch "$target_marker.packing"
+		if [ "$pref_archive" == "true" ] && [ "$pref_read_only" != "true" ]; then
+			touch "$marker.packing"
 			tar \
-				-czf "$target_dir.tar.gz"\
-				-C "$target_dir_path" \
+				-czf "$source.tar.gz"\
+				-C "$source_path" \
 				--exclude=".tmpfize*" \
-				"$target_dir_name"
-			rm "$target_marker.packing"
+				"$source_name"
+			rm "$marker.packing"
 			
-			[ "$save_disk_copy" ] || rm -r "$target_dir"
+			[ "$pref_save_on_disk" ] || rm -r "$source"
 		fi
 	fi
 
-	if [ "$1" -ge 1 ]; then
-		[ "$1" -lt 5 ] && exit 1
-	fi
+	[ "$1" -ge 1 ] && [ "$1" -lt 5 ] && exit 1
 }
 
 # Background synchronization
 function background_sync {
 	count=0
-	while [ -e "$target_marker" ]; do
-		if [ ! "$read_only" ] && [ "$sync_interval" -gt 0 ]; then
-			if [ "$count" -lt "$sync_interval" ]; then
+	while [ -e "$marker" ]; do
+		if [ ! "$pref_read_only" ] && [ "$pref_sync_delay" -gt 0 ]; then
+			if [ "$count" -lt "$pref_sync_delay" ]; then
 				count=$((count+1))
 			else
 				rsync -ax --delete \
-					--exclude $(get_name "$target_marker") \
-					"$target_dir/" "$backup_dir"
+					--exclude $(get_name "$marker") \
+					"$source/" "$backup"
 				count=0
 			fi
 		fi
@@ -203,91 +194,86 @@ function background_sync {
 
 # Run process and keep tmpfize alive until it finishes
 function process_watcher {
-	if [ "$execute" ]; then
-		out 1 "[Info] Starting command ($execute)"
-		$execute > /dev/null 2>&1
-		[ -e "$target_marker" ] && rm "$target_marker"
+	if [ "$pref_execute" ]; then
+		log 1 "[Info] Starting command ($pref_execute)"
+		$pref_execute > /dev/null 2>&1
+		[ -e "$marker" ] && rm "$marker"
 	fi
 }
 
 ###############################
-# Moving $target_dir to tmpfs #
+# Moving $source to tmpfs #
 ###############################
 
 # Level 1: Check if directory is already mouted
-out 1 "[Info] Checking if $target_dir_name is already mounted"
-if [ -e "$target_marker" ]; then
-	out 0 "[Error] $target_dir is already mounted!"
-	
+log 1 "[Info] Checking if $source_name is already mounted"
+if [ -e "$marker" ]; then
+	log 0 "[Error] $source is already mounted!"
 	back_sequence 1
 fi
 
 # Restore backup if exists and create if not
-out 1 "[Info] Checking if backup of $target_dir_name exists"
-if [ -e "$backup_dir" ]; then
-	out 0 "[Warning] Backup of $target_dir_name is found. Restoring..."
+log 1 "[Info] Checking if backup of $source_name exists"
+if [ -e "$backup" ]; then
+	log 0 "[Warning] Backup of $source_name is found. Restoring..."
 
-	if [ ! -d "$target_dir" ]; then
-		rm "$target_dir"
-		mv "$backup_dir" "$target_dir"
+	if [ ! -d "$source" ]; then
+		rm "$source"
+		mv "$backup" "$source"
 	else
-		rsync -ax "$backup_dir/" "$target_dir" \
-			&& rm -r "$backup_dir"
+		rsync -ax "$backup/" "$source" \
+			&& rm -r "$backup"
 	fi
 fi
-[ ! -e "$target_dir" ] && mkdir -p "$target_dir"
+[ ! -e "$source" ] && mkdir -p "$source"
 
 # Check free space in tmpfs
-target_dir_size=$(du -s "$target_dir" | awk '{print $1}' || echo 0)
-
-if [ $target_dir_size -ge $tmpfs_max_size ]; then
-	out 0 "[Error] Not enough space in tmpfs!"
+source_size=$(du -s "$source" | awk '{print $1}' || echo 0)
+if [ $source_size -ge $tmpfs_max_size ]; then
+	log 0 "[Error] Not enough space in tmpfs!"
 	exit 1
 fi
 
 # Level 2: Copying files from target directory to tmpfs
 
 # Unpack archive if passed as main argument
-if [ "$archive" == "true" ]; then
-	if [ -e "$target_dir.tar.gz" ]; then
-		out 1 "[Info] Unpacking archive $target_dir_name.tar.gz"
-		if ! tar --keep-newer-files -xzf "$target_dir.tar.gz" -C "$target_dir_path"; then
-			out 0 "[Error] Can't unpack archive $target_dir_name.tar.gz!"
+if [ "$pref_archive" == "true" ]; then
+	if [ -e "$source.tar.gz" ]; then
+		log 1 "[Info] Unpacking archive $source_name.tar.gz"
+		if ! tar --keep-newer-files -xzf "$source.tar.gz" -C "$source_path"; then
+			log 0 "[Error] Can't unpack archive $source_name.tar.gz!"
 
 			back_sequence 2
 		fi
 	else
-		out 1 "[Info] Archive $target_dir_name.tar.gz not found. It will be created after unmount"
+		log 1 "[Info] Archive $source_name.tar.gz not found. It will be created after unmount"
 	fi
 fi
 
-out 1 "[Info] Copying files from $target_dir_name to tmpfs"
-if ! rsync -ax --delete "$target_dir/" "$target_tmpfs"; then
-	out 0 "[Error] Can't copy $target_dir_name to tmpfs!"
-
+log 1 "[Info] Copying files from $source_name to tmpfs"
+if ! rsync -ax --delete "$source/" "$target"; then
+	log 0 "[Error] Can't copy $source_name to tmpfs!"
 	back_sequence 2
 fi
 
 # Level 3: Moving target directory from the way
-out 1 "[Info] Renaming $target_dir_name to $(get_name $backup_dir)"
-if ! mv "$target_dir" "$backup_dir"; then
-	out 0 "[Error] Can't move $target_dir_name to $(get_name $backup_dir)"
-	
+log 1 "[Info] Renaming $source_name to $(get_name $backup)"
+if ! mv "$source" "$backup"; then
+	log 0 "[Error] Can't move $source_name to $(get_name $backup)"
 	back_sequence 3
 fi
 
 # Level 4: Mounting tmpfs into target directory
-out 1 "[Info] Creating symbolic link from $target_dir_name to tmpfs"
-if ! ln -s "$target_tmpfs" "$target_dir"; then
-	out 0 "[Error] Can't create symlink: $target_dir"
-	
+log 1 "[Info] Creating symbolic link from $source_name to tmpfs"
+if ! ln -s "$target" "$source"; then
+	log 0 "[Error] Can't create symlink: $source"
 	back_sequence 4
 fi
 
 # Level 5: Run periodic synchronization in background
-echo "You can unmount current directory by removing this file" > "$target_marker"
+echo "You can unmount current directory by removing this file" > "$marker"
 background_sync &
-out 1 "[Info] Background synchronization started (PID=$!)"
+log 1 "[Info] Background synchronization started (PID=$!)"
 
 # Run process (if set)
 process_watcher &
